name: update_wishlists
on:
  # push
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update_wishlists:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main, including submodule
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Configure Git
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.NAME }}"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node.js Dependencies
        run: |
          cd wishlist_splitter/data/origin_traits
          npm install
          cd ../../..

      - name: Update Git Submodules
        run: git submodule update --remote

      - name: Run JavaScript Script
        run: |
          cd wishlist_splitter/data/origin_traits
          node generate_origin_traits.js
          cd ../../..

      - name: Commit Origin Trait Changes
        run: |
          git add .
          git commit -m "update origin traits" || echo "No changes to commit"
          git push

      - name: Run Python Script
        run: |
          python3 wishlist_splitter/main.py

      - name: Commit Wishlist Changes and Push
        run: |
          git add .
          git commit -m "Update alongside dim-wish-list-sources by 48klocs" || echo "No changes to commit"
          git push
