name: update_wishlists
on:
  # push
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update_wishlists:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Branch, Including Submodule
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Configure Git
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.NAME }}"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node.js Dependencies
        run: |
          cd wishlist_splitter/data/weapon_mods
          npm install
          cd ../../..

      - name: Update Weapon Mods
        run: |
          node wishlist_splitter/data/weapon_mods/get_weapon_mods.js

      - name: Commit and Push Weapon Mod Update
        run: |
          git add .
          git commit -m "Update weapon mods alongside Destiny Data Explorer" || echo "No changes to commit"
          git push

      - name: Update dim-wish-list-sources Submodule
        run: git submodule update --remote

      - name: Update Wishlists
        run: |
          python3 wishlist_splitter/main.py

      - name: Commit and Push Wishlist Update
        run: |
          git add .
          git commit -m "Update wishlists alongside dim-wish-list-sources" || echo "No changes to commit"
          git push
